apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MANUFACTURERID
              value: "BPNL0000000007UH"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: dft-postgresql-secrets
                  key: dbUrl
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dft-postgresql-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dft-postgresql-secrets
                  key: password
            #- name: SPRING_DATASOURCE_POSTGRESPASSWORD
            #  valueFrom:
               # secretKeyRef:
                #  name: dft-postgresql-secrets
                 # key: postgresPassword
            - name: DIGITAL-TWINS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: digitalTwinHostname
            - name: DIGITAL-TWINS_AUTHENTICATION_URL
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: digitalTwinAuthorizationUrl
            - name: DIGITAL-TWINS_AUTHENTICATION_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: digitalTwinAuthorizationClientId
            - name: DIGITAL-TWINS_AUTHENTICATION_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: digitalTwinAuthorizationClientSecret
            - name: DIGITAL-TWINS_AUTHENTICATION_GRANTTYPE
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: digitalTwinsAuthenticationGrantType
            - name: EDC_ENABLED
              value: 'true'
            - name: EDC_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcHostname
            - name: EDC_APIKEYHEADER
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcApiKeyHeader
            - name: EDC_APIKEY
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcApiKey
            - name: DFT_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcDftHostname
            - name: DFT_APIKEYHEADER
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcDftApiKeyHeader
            - name: DFT_APIKEY
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcDftApiKey
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: keycloakREALM
            - name: KEYCLOAK_RESOURCE
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: keycloakAUTH
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: keycloakURL   
            - name: KEYCLOAK_SSL-REQUIRED
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: keycloakSSL  
            - name: EDC_CONSUMER_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcconshost
            - name: EDC_CONSUMER_APIKEY
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcconsapikey
            - name: EDC_CONSUMER_DATAURI
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcconsdatauri
            - name: EDC_CONSUMER_APIKEYHEADER
              valueFrom:
                secretKeyRef:
                  name: dft-edc-secrets
                  key: edcconsapiheader
            - name: CLIENTID
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: portalApiID 
            - name: CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: portalApisecret  
            - name: PARTNER_POOL_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: partnerpoolhostURL
            - name: PORTAL_BACKEND_HOSTNAME 
              valueFrom:
                secretKeyRef:
                  name: dtf-digitaltwins-secrets
                  key: portalpoolhostURL 
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.endpoint }}
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          # @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.endpoint }}
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
